import os

# DATABASE
DB_HOST = os.environ['IBGE_DB_HOST']
DB_NAME = os.environ['IBGE_DB_NAME']
DB_USER = os.environ['IBGE_DB_USER']
DB_PASSWORD = os.environ['IBGE_DB_PASSWORD']

# PATH TO THE IBGE SHAPEFILES
SHP_PATH = os.environ['IBGE_SHP_PATH']

# MAPBOX ACCOUNT
MAPBOX_TOKEN = os.environ['MAPBOX_TOKEN']
MAPBOX_USERNAME = os.environ['MAPBOX_USERNAME']
